// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolucionProductividad.Persistencia.Contexto;

#nullable disable

namespace SolucionProductividad.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoProductividad))]
    [Migration("20260924174019_ProyectosSoporte")]
    partial class ProyectosSoporte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ArchivoAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjDocumentoId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AdjFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("MensajeTicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjMensajeTicketId");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AdjNombreArchivo");

                    b.Property<Guid?>("RegistroDiarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjRegistroDiarioId");

                    b.Property<string>("RutaFirebaseStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AdjRutaFirebaseStorage");

                    b.Property<Guid>("SubidoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjSubidoPor");

                    b.Property<long>("TamanoEnBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("AdjTamanoEnBytes");

                    b.Property<Guid?>("TareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjTareaId");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjTicketId");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AdjTipoContenido");

                    b.Property<string>("UrlDescarga")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AdjUrlDescarga");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("MensajeTicketId");

                    b.HasIndex("RegistroDiarioId");

                    b.HasIndex("SubidoPor");

                    b.HasIndex("TareaId");

                    b.HasIndex("TicketId");

                    b.ToTable("ArchivosAdjuntos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ArchivoModificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AmoId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("LineasAgregadas")
                        .HasColumnType("int")
                        .HasColumnName("AmoLineasAgregadas");

                    b.Property<int>("LineasEliminadas")
                        .HasColumnType("int")
                        .HasColumnName("AmoLineasEliminadas");

                    b.Property<string>("Parche")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AmoParche");

                    b.Property<Guid>("RamaTicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AmoRamaTicketId");

                    b.Property<string>("RutaAnterior")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AmoRutaAnterior");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AmoRutaArchivo");

                    b.Property<string>("TipoCambio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AmoTipoCambio");

                    b.HasKey("Id");

                    b.HasIndex("RamaTicketId");

                    b.ToTable("ArchivosModificados");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Carpeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CrpId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CrpFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CrpIcono");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("CrpIndiceOrden");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CrpNombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CrpProyectoId");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Carpetas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.CarpetaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CdoId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("CarpetaPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CdoCarpetaPadreId");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CdoColor");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CdoFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("CdoIndiceOrden");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CdoNombre");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CdoUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaPadreId");

                    b.HasIndex("UsuarioId", "CarpetaPadreId");

                    b.ToTable("CarpetasDocumento");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ColaSoporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClaId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ClaDescripcion");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit")
                        .HasColumnName("ClaEstaActiva");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ClaNombre");

                    b.HasKey("Id");

                    b.ToTable("ColasSoporte");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c0a7e10-2b6f-4d1e-9a51-000000000001"),
                            Descripcion = "Cola por defecto para todos los tickets.",
                            EstaActiva = true,
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.CommitRama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CmtId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("CmtAutor");

                    b.Property<DateTime>("FechaCommit")
                        .HasColumnType("datetime2")
                        .HasColumnName("CmtFechaCommit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CmtMensaje");

                    b.Property<Guid>("RamaTicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CmtRamaTicketId");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("CmtSha");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CmtUrl");

                    b.HasKey("Id");

                    b.HasIndex("RamaTicketId");

                    b.ToTable("CommitsRama");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DespliegueTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DspId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DspAmbiente");

                    b.Property<Guid>("DesplegadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DspDesplegadoPor");

                    b.Property<Guid?>("EvaluadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DspEvaluadoPor");

                    b.Property<DateTime>("FechaDespliegue")
                        .HasColumnType("datetime2")
                        .HasColumnName("DspFechaDespliegue");

                    b.Property<DateTime?>("FechaResultado")
                        .HasColumnType("datetime2")
                        .HasColumnName("DspFechaResultado");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("DspNotas");

                    b.Property<string>("NotasResultado")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("DspNotasResultado");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DspReferencia");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DspResultado");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DspTicketId");

                    b.HasKey("Id");

                    b.HasIndex("DesplegadoPor");

                    b.HasIndex("EvaluadoPor");

                    b.HasIndex("TicketId");

                    b.ToTable("DesplieguesTicket");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DocumentoEtiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DteId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DteDocumentoId");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DteEtiquetaId");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("DocumentoId", "EtiquetaId")
                        .IsUnique();

                    b.ToTable("DocumentosEtiquetas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("CarpetaDocumentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocCarpetaDocumentoId");

                    b.Property<string>("ContenidoMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DocContenidoMarkdown");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocCreadoPor");

                    b.Property<Guid?>("DocumentoPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocDocumentoPadreId");

                    b.Property<bool>("EstaArchivado")
                        .HasColumnType("bit")
                        .HasColumnName("DocEstaArchivado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DocFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaArchivado")
                        .HasColumnType("datetime2")
                        .HasColumnName("DocFechaArchivado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DocFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DocIcono");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocProyectoId");

                    b.Property<string>("RutaEsquema")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)")
                        .HasColumnName("DocRutaEsquema");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DocTitulo");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaDocumentoId");

                    b.HasIndex("DocumentoPadreId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("Titulo");

                    b.HasIndex("CreadoPor", "RutaEsquema")
                        .IsUnique();

                    b.HasIndex("CreadoPor", "EstaArchivado", "CarpetaDocumentoId");

                    b.ToTable("DocumentosMarkdown");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.EtiquetaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EtqId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EtqColor");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("EtqFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EtqNombre");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EtqUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nombre")
                        .IsUnique();

                    b.ToTable("EtiquetasDocumento");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.EventoTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EvtId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Comentario")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("EvtComentario");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EvtDescripcion");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("EvtEstadoAnterior");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("EvtEstadoNuevo");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2")
                        .HasColumnName("EvtFechaEvento");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EvtTicketId");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("EvtTipoEvento");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EvtUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TicketId", "FechaEvento");

                    b.ToTable("EventosTicket");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LstId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("CarpetaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LstCarpetaId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LstFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("LstIndiceOrden");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LstNombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LstProyectoId");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ListasTareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Marcador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MrcId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MrcEntidadId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("MrcFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("MrcIndiceOrden");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MrcTipoEntidad");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MrcTitulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MrcUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "TipoEntidad", "EntidadId")
                        .IsUnique();

                    b.ToTable("Marcadores");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.MensajeTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MsgId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CorreoRemitente")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("MsgCorreoRemitente");

                    b.Property<string>("CuerpoMensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgCuerpoMensaje");

                    b.Property<bool>("EsNotaInterna")
                        .HasColumnType("bit")
                        .HasColumnName("MsgEsNotaInterna");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("MsgFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreRemitente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("MsgNombreRemitente");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MsgTicketId");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MsgUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensajesTicket");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.PoliticaSla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SlaId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit")
                        .HasColumnName("SlaEstaActiva");

                    b.Property<int>("MinutosPrimeraRespuesta")
                        .HasColumnType("int")
                        .HasColumnName("SlaMinutosPrimeraRespuesta");

                    b.Property<int>("MinutosResolucion")
                        .HasColumnType("int")
                        .HasColumnName("SlaMinutosResolucion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SlaNombre");

                    b.HasKey("Id");

                    b.ToTable("PoliticasSla");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c0a7e10-2b6f-4d1e-9a51-000000000101"),
                            EstaActiva = true,
                            MinutosPrimeraRespuesta = 60,
                            MinutosResolucion = 480,
                            Nombre = "Urgente"
                        },
                        new
                        {
                            Id = new Guid("5c0a7e10-2b6f-4d1e-9a51-000000000102"),
                            EstaActiva = true,
                            MinutosPrimeraRespuesta = 240,
                            MinutosResolucion = 1440,
                            Nombre = "Alta"
                        },
                        new
                        {
                            Id = new Guid("5c0a7e10-2b6f-4d1e-9a51-000000000103"),
                            EstaActiva = true,
                            MinutosPrimeraRespuesta = 480,
                            MinutosResolucion = 4320,
                            Nombre = "Media"
                        },
                        new
                        {
                            Id = new Guid("5c0a7e10-2b6f-4d1e-9a51-000000000104"),
                            EstaActiva = true,
                            MinutosPrimeraRespuesta = 1440,
                            MinutosResolucion = 7200,
                            Nombre = "Baja"
                        });
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PryId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ClavePrefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PryClavePrefijo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PryDescripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("PryFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PryNombre");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PryPropietarioId");

                    b.HasKey("Id");

                    b.HasIndex("PropietarioId", "ClavePrefijo")
                        .IsUnique();

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ProyectoSoporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PsoId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PsoColor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PsoDescripcion");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("PsoEstaActivo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("PsoFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PsoNombre");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PsoUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nombre")
                        .IsUnique();

                    b.ToTable("ProyectosSoporte");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RamaTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RtkId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RtkCreadoPor");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("RtkFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaUltimaSincronizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("RtkFechaUltimaSincronizacion");

                    b.Property<int>("LineasAgregadas")
                        .HasColumnType("int")
                        .HasColumnName("RtkLineasAgregadas");

                    b.Property<int>("LineasEliminadas")
                        .HasColumnType("int")
                        .HasColumnName("RtkLineasEliminadas");

                    b.Property<string>("NombreRama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RtkNombreRama");

                    b.Property<string>("PullRequestEstado")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RtkPullRequestEstado");

                    b.Property<DateTime?>("PullRequestFechaFusion")
                        .HasColumnType("datetime2")
                        .HasColumnName("RtkPullRequestFechaFusion");

                    b.Property<int?>("PullRequestNumero")
                        .HasColumnType("int")
                        .HasColumnName("RtkPullRequestNumero");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RtkPullRequestUrl");

                    b.Property<string>("RamaBase")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RtkRamaBase");

                    b.Property<string>("RamaDestino")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RtkRamaDestino");

                    b.Property<Guid>("RepositorioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RtkRepositorioId");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RtkTicketId");

                    b.Property<int>("TotalArchivos")
                        .HasColumnType("int")
                        .HasColumnName("RtkTotalArchivos");

                    b.Property<int>("TotalCommits")
                        .HasColumnType("int")
                        .HasColumnName("RtkTotalCommits");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("RepositorioId");

                    b.HasIndex("TicketId", "RepositorioId", "NombreRama")
                        .IsUnique();

                    b.ToTable("RamasTicket");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ReferenciaEntidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RefId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RefDestinoId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("RefFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("OrigenId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RefOrigenId");

                    b.Property<string>("TipoDestino")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("RefTipoDestino");

                    b.Property<string>("TipoOrigen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("RefTipoOrigen");

                    b.HasKey("Id");

                    b.HasIndex("TipoDestino", "DestinoId");

                    b.HasIndex("TipoOrigen", "OrigenId");

                    b.ToTable("ReferenciasEntidades");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LogId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContenidoMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogContenidoMarkdown");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LogFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LogFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("FechaLog")
                        .HasColumnType("date")
                        .HasColumnName("LogFechaLog");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LogUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaLog")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_FechaLog");

                    b.ToTable("RegistrosDiarios");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroTiempo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RgtId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RgtDescripcion");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("RgtFechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("RgtFechaInicio");

                    b.Property<int?>("MinutosTranscurridos")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("RgtMinutosTranscurridos")
                        .HasComputedColumnSql("DATEDIFF(MINUTE, [RgtFechaInicio], [RgtFechaFin])");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RgtTareaId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RgtUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId", "FechaInicio");

                    b.ToTable("RegistrosTiempo");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Repositorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RepId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("RepEstaActivo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("RepFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RepNombre");

                    b.Property<string>("NombreRepositorio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RepNombreRepositorio");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RepPropietario");

                    b.Property<Guid?>("ProyectoSoporteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RepProyectoSoporteId");

                    b.Property<string>("RamaDesarrollo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RepRamaDesarrollo");

                    b.Property<string>("RamaPrincipal")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RepRamaPrincipal");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RepUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoSoporteId");

                    b.HasIndex("UsuarioId", "Propietario", "NombreRepositorio")
                        .IsUnique();

                    b.ToTable("Repositorios");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RolId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RolDescripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("RolFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RolNombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0001"),
                            Descripcion = "Acceso total, gestión de usuarios y roles.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0002"),
                            Descripcion = "Atiende tickets de soporte.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Agente"
                        },
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0003"),
                            Descripcion = "Gestiona sus tareas, documentos y bóveda.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Miembro"
                        });
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.SecretoBoveda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BvdId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BvdCreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("BvdDescripcion");

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("BvdEntorno");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("BvdFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("BvdFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreClave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("BvdNombreClave");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BvdProyectoId");

                    b.Property<string>("ValorCifrado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BvdValorCifrado");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ProyectoId", "Entorno", "NombreClave")
                        .IsUnique();

                    b.ToTable("BovedaSecretos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TarId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TarCreadoPor");

                    b.Property<string>("DescripcionMarkdown")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TarDescripcionMarkdown");

                    b.Property<bool>("EsImportante")
                        .HasColumnType("bit")
                        .HasColumnName("TarEsImportante");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("bit")
                        .HasColumnName("TarEsUrgente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TarEstado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TarFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TarFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("TarFechaVencimiento");

                    b.Property<decimal?>("HorasEstimadas")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("TarHorasEstimadas");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("TarIndiceOrden");

                    b.Property<Guid>("ListaTareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TarListaTareaId");

                    b.Property<int>("NumeroTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TarNumeroTarea");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTarea"), 100L);

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TarPrioridad");

                    b.Property<Guid?>("TareaPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TarTareaPadreId");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TarTitulo");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("NumeroTarea")
                        .IsUnique();

                    b.HasIndex("TareaPadreId");

                    b.HasIndex("ListaTareaId", "IndiceOrden");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("AgenteAsignadoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckAgenteAsignadoId");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TckAsunto");

                    b.Property<Guid>("ColaSoporteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckColaSoporteId");

                    b.Property<string>("CorreoSolicitante")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TckCorreoSolicitante");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckCreadoPor");

                    b.Property<string>("DescripcionMarkdown")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TckDescripcionMarkdown");

                    b.Property<string>("DocumentacionMarkdown")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TckDocumentacionMarkdown");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TckEstado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaCierre");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaLimitePrimeraRespuesta")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaLimitePrimeraRespuesta");

                    b.Property<DateTime?>("FechaLimiteResolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaLimiteResolucion");

                    b.Property<DateTime?>("FechaPrimeraRespuesta")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaPrimeraRespuesta");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaResolucion");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaVencimiento");

                    b.Property<decimal?>("HorasDedicadas")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("TckHorasDedicadas");

                    b.Property<string>("IdSeguimiento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TckIdSeguimiento");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TckNombreSolicitante");

                    b.Property<string>("NumeroExterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TckNumeroExterno");

                    b.Property<int>("NumeroTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TckNumeroTicket");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTicket"), 1000L);

                    b.Property<Guid?>("PoliticaSlaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckPoliticaSlaId");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TckPrioridad");

                    b.Property<Guid?>("TareaRelacionadaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckTareaRelacionadaId");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TckTipo");

                    b.HasKey("Id");

                    b.HasIndex("ColaSoporteId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroExterno");

                    b.HasIndex("NumeroTicket")
                        .IsUnique();

                    b.HasIndex("PoliticaSlaId");

                    b.HasIndex("TareaRelacionadaId");

                    b.HasIndex("AgenteAsignadoId", "Estado");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.TicketProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TprId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ProyectoSoporteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TprProyectoSoporteId");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TprTicketId");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoSoporteId");

                    b.HasIndex("TicketId", "ProyectoSoporteId")
                        .IsUnique();

                    b.ToTable("TicketsProyectos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.TokenRefresco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TkrId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TkrFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TkrFechaExpiracion");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TkrFechaRevocacion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("TkrTokenHash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TkrUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRefresco");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UsuCorreo");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("UsuEstaActivo");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UsuFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UsuFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UsuFechaUltimoAcceso");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UsuHashContrasena");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("UsuNombreCompleto");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("UsuNombreUsuario");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UroId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UroFechaAsignacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UroRolId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UroUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.VersionDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VdoId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContenidoMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VdoContenidoMarkdown");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VdoCreadoPor");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VdoDocumentoId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("VdoFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("int")
                        .HasColumnName("VdoNumeroVersion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("VdoTitulo");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("DocumentoId", "NumeroVersion")
                        .IsUnique();

                    b.ToTable("VersionesDocumento");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ArchivoAdjunto", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", null)
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.MensajeTicket", null)
                        .WithMany()
                        .HasForeignKey("MensajeTicketId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.RegistroDiario", null)
                        .WithMany()
                        .HasForeignKey("RegistroDiarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("SubidoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ArchivoModificado", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.RamaTicket", null)
                        .WithMany("Archivos")
                        .HasForeignKey("RamaTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Carpeta", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.CarpetaDocumento", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.CarpetaDocumento", null)
                        .WithMany()
                        .HasForeignKey("CarpetaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.CommitRama", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.RamaTicket", null)
                        .WithMany("Commits")
                        .HasForeignKey("RamaTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DespliegueTicket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DesplegadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EvaluadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DocumentoEtiqueta", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", null)
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.EtiquetaDocumento", null)
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.CarpetaDocumento", null)
                        .WithMany()
                        .HasForeignKey("CarpetaDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", null)
                        .WithMany()
                        .HasForeignKey("DocumentoPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.EtiquetaDocumento", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.EventoTicket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Carpeta", null)
                        .WithMany()
                        .HasForeignKey("CarpetaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", "Proyecto")
                        .WithMany("ListasTareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Marcador", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.MensajeTicket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Ticket", null)
                        .WithMany("Mensajes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Proyecto", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ProyectoSoporte", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RamaTicket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Repositorio", "Repositorio")
                        .WithMany()
                        .HasForeignKey("RepositorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repositorio");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroDiario", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroTiempo", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Repositorio", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.ProyectoSoporte", null)
                        .WithMany()
                        .HasForeignKey("ProyectoSoporteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.SecretoBoveda", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.ListaTareas", "ListaTareas")
                        .WithMany("Tareas")
                        .HasForeignKey("ListaTareaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", "TareaPadre")
                        .WithMany("Subtareas")
                        .HasForeignKey("TareaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ListaTareas");

                    b.Navigation("TareaPadre");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AgenteAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.ColaSoporte", null)
                        .WithMany()
                        .HasForeignKey("ColaSoporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.PoliticaSla", null)
                        .WithMany()
                        .HasForeignKey("PoliticaSlaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaRelacionadaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.TicketProyecto", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.ProyectoSoporte", null)
                        .WithMany()
                        .HasForeignKey("ProyectoSoporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.TokenRefresco", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.VersionDocumento", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", null)
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Proyecto", b =>
                {
                    b.Navigation("ListasTareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RamaTicket", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Commits");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.Navigation("Subtareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
