// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolucionProductividad.Persistencia.Contexto;

#nullable disable

namespace SolucionProductividad.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoProductividad))]
    [Migration("20260924012242_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ArchivoAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ADJ_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ADJ_DocumentoId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ADJ_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("MensajeTicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ADJ_MensajeTicketId");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADJ_NombreArchivo");

                    b.Property<Guid?>("RegistroDiarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ADJ_RegistroDiarioId");

                    b.Property<string>("RutaFirebaseStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ADJ_RutaFirebaseStorage");

                    b.Property<Guid>("SubidoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ADJ_SubidoPor");

                    b.Property<long>("TamanoEnBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("ADJ_TamanoEnBytes");

                    b.Property<Guid?>("TareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ADJ_TareaId");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ADJ_TipoContenido");

                    b.Property<string>("UrlDescarga")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ADJ_UrlDescarga");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("MensajeTicketId");

                    b.HasIndex("RegistroDiarioId");

                    b.HasIndex("SubidoPor");

                    b.HasIndex("TareaId");

                    b.ToTable("ArchivosAdjuntos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Carpeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CRP_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CRP_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CRP_Icono");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("CRP_IndiceOrden");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CRP_Nombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CRP_ProyectoId");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Carpetas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ColaSoporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CLA_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("CLA_Descripcion");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit")
                        .HasColumnName("CLA_EstaActiva");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CLA_Nombre");

                    b.HasKey("Id");

                    b.ToTable("ColasSoporte");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DOC_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContenidoMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOC_ContenidoMarkdown");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DOC_CreadoPor");

                    b.Property<Guid?>("DocumentoPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DOC_DocumentoPadreId");

                    b.Property<bool>("EstaArchivado")
                        .HasColumnType("bit")
                        .HasColumnName("DOC_EstaArchivado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DOC_FechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DOC_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DOC_Icono");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DOC_ProyectoId");

                    b.Property<string>("RutaEsquema")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)")
                        .HasColumnName("DOC_RutaEsquema");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DOC_Titulo");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("DocumentoPadreId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("RutaEsquema")
                        .IsUnique();

                    b.HasIndex("Titulo");

                    b.ToTable("DocumentosMarkdown");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LST_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("CarpetaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LST_CarpetaId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LST_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("LST_IndiceOrden");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LST_Nombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LST_ProyectoId");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ListasTareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Marcador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MRC_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MRC_EntidadId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("MRC_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("MRC_IndiceOrden");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MRC_TipoEntidad");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MRC_Titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MRC_UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "TipoEntidad", "EntidadId")
                        .IsUnique();

                    b.ToTable("Marcadores");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.MensajeTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MSG_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CorreoRemitente")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("MSG_CorreoRemitente");

                    b.Property<string>("CuerpoMensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MSG_CuerpoMensaje");

                    b.Property<bool>("EsNotaInterna")
                        .HasColumnType("bit")
                        .HasColumnName("MSG_EsNotaInterna");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("MSG_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreRemitente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("MSG_NombreRemitente");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MSG_TicketId");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("MensajesTicket");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.PoliticaSla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SLA_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit")
                        .HasColumnName("SLA_EstaActiva");

                    b.Property<int>("MinutosPrimeraRespuesta")
                        .HasColumnType("int")
                        .HasColumnName("SLA_MinutosPrimeraRespuesta");

                    b.Property<int>("MinutosResolucion")
                        .HasColumnType("int")
                        .HasColumnName("SLA_MinutosResolucion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SLA_Nombre");

                    b.HasKey("Id");

                    b.ToTable("PoliticasSla");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PRY_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ClavePrefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PRY_ClavePrefijo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PRY_Descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("PRY_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PRY_Nombre");

                    b.HasKey("Id");

                    b.HasIndex("ClavePrefijo")
                        .IsUnique();

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ReferenciaEntidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_DestinoId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("REF_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("OrigenId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_OrigenId");

                    b.Property<string>("TipoDestino")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("REF_TipoDestino");

                    b.Property<string>("TipoOrigen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("REF_TipoOrigen");

                    b.HasKey("Id");

                    b.HasIndex("TipoDestino", "DestinoId");

                    b.HasIndex("TipoOrigen", "OrigenId");

                    b.ToTable("ReferenciasEntidades");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LOG_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContenidoMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOG_ContenidoMarkdown");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LOG_FechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LOG_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("FechaLog")
                        .HasColumnType("date")
                        .HasColumnName("LOG_FechaLog");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LOG_UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaLog")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_FechaLog");

                    b.ToTable("RegistrosDiarios");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroTiempo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RGT_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RGT_Descripcion");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("RGT_FechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("RGT_FechaInicio");

                    b.Property<int?>("MinutosTranscurridos")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("RGT_MinutosTranscurridos")
                        .HasComputedColumnSql("DATEDIFF(MINUTE, [RGT_FechaInicio], [RGT_FechaFin])");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RGT_TareaId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RGT_UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId", "FechaInicio");

                    b.ToTable("RegistrosTiempo");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ROL_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ROL_Descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ROL_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ROL_Nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0001"),
                            Descripcion = "Acceso total, gestión de usuarios y roles.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0002"),
                            Descripcion = "Atiende tickets de soporte.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Agente"
                        },
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0003"),
                            Descripcion = "Gestiona sus tareas, documentos y bóveda.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Miembro"
                        });
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.SecretoBoveda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BVD_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BVD_CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("BVD_Descripcion");

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("BVD_Entorno");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("BVD_FechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("BVD_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreClave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("BVD_NombreClave");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BVD_ProyectoId");

                    b.Property<string>("ValorCifrado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BVD_ValorCifrado");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ProyectoId", "Entorno", "NombreClave")
                        .IsUnique();

                    b.ToTable("BovedaSecretos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAR_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAR_CreadoPor");

                    b.Property<string>("DescripcionMarkdown")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TAR_DescripcionMarkdown");

                    b.Property<bool>("EsImportante")
                        .HasColumnType("bit")
                        .HasColumnName("TAR_EsImportante");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("bit")
                        .HasColumnName("TAR_EsUrgente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TAR_Estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TAR_FechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TAR_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("TAR_FechaVencimiento");

                    b.Property<decimal?>("HorasEstimadas")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("TAR_HorasEstimadas");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("TAR_IndiceOrden");

                    b.Property<Guid>("ListaTareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAR_ListaTareaId");

                    b.Property<int>("NumeroTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TAR_NumeroTarea");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTarea"), 100L);

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TAR_Prioridad");

                    b.Property<Guid?>("TareaPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAR_TareaPadreId");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TAR_Titulo");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("NumeroTarea")
                        .IsUnique();

                    b.HasIndex("TareaPadreId");

                    b.HasIndex("ListaTareaId", "IndiceOrden");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TCK_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("AgenteAsignadoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TCK_AgenteAsignadoId");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TCK_Asunto");

                    b.Property<Guid>("ColaSoporteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TCK_ColaSoporteId");

                    b.Property<string>("CorreoSolicitante")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TCK_CorreoSolicitante");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TCK_Estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TCK_FechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TCK_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaLimitePrimeraRespuesta")
                        .HasColumnType("datetime2")
                        .HasColumnName("TCK_FechaLimitePrimeraRespuesta");

                    b.Property<DateTime?>("FechaLimiteResolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TCK_FechaLimiteResolucion");

                    b.Property<DateTime?>("FechaPrimeraRespuesta")
                        .HasColumnType("datetime2")
                        .HasColumnName("TCK_FechaPrimeraRespuesta");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TCK_FechaResolucion");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TCK_NombreSolicitante");

                    b.Property<int>("NumeroTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TCK_NumeroTicket");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTicket"), 1000L);

                    b.Property<Guid?>("PoliticaSlaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TCK_PoliticaSlaId");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TCK_Prioridad");

                    b.Property<Guid?>("TareaRelacionadaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TCK_TareaRelacionadaId");

                    b.HasKey("Id");

                    b.HasIndex("ColaSoporteId");

                    b.HasIndex("NumeroTicket")
                        .IsUnique();

                    b.HasIndex("PoliticaSlaId");

                    b.HasIndex("TareaRelacionadaId");

                    b.HasIndex("AgenteAsignadoId", "Estado");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.TokenRefresco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TKR_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TKR_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TKR_FechaExpiracion");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TKR_FechaRevocacion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("TKR_TokenHash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TKR_UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRefresco");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USR_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("USR_Correo");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("USR_EstaActivo");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("USR_FechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("USR_FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("USR_FechaUltimoAcceso");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("USR_HashContrasena");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("USR_NombreCompleto");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("URO_Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("URO_FechaAsignacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("URO_RolId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("URO_UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ArchivoAdjunto", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", null)
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.MensajeTicket", null)
                        .WithMany()
                        .HasForeignKey("MensajeTicketId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.RegistroDiario", null)
                        .WithMany()
                        .HasForeignKey("RegistroDiarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("SubidoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Carpeta", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", null)
                        .WithMany()
                        .HasForeignKey("DocumentoPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Carpeta", null)
                        .WithMany()
                        .HasForeignKey("CarpetaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", "Proyecto")
                        .WithMany("ListasTareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Marcador", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.MensajeTicket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Ticket", null)
                        .WithMany("Mensajes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroDiario", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroTiempo", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.SecretoBoveda", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.ListaTareas", "ListaTareas")
                        .WithMany("Tareas")
                        .HasForeignKey("ListaTareaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", "TareaPadre")
                        .WithMany("Subtareas")
                        .HasForeignKey("TareaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ListaTareas");

                    b.Navigation("TareaPadre");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AgenteAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.ColaSoporte", null)
                        .WithMany()
                        .HasForeignKey("ColaSoporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.PoliticaSla", null)
                        .WithMany()
                        .HasForeignKey("PoliticaSlaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaRelacionadaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.TokenRefresco", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Proyecto", b =>
                {
                    b.Navigation("ListasTareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.Navigation("Subtareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
