// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolucionProductividad.Persistencia.Contexto;

#nullable disable

namespace SolucionProductividad.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoProductividad))]
    [Migration("20260924024304_ConvencionColumnasYNombreUsuario")]
    partial class ConvencionColumnasYNombreUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ArchivoAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjDocumentoId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AdjFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("MensajeTicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjMensajeTicketId");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AdjNombreArchivo");

                    b.Property<Guid?>("RegistroDiarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjRegistroDiarioId");

                    b.Property<string>("RutaFirebaseStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AdjRutaFirebaseStorage");

                    b.Property<Guid>("SubidoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjSubidoPor");

                    b.Property<long>("TamanoEnBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("AdjTamanoEnBytes");

                    b.Property<Guid?>("TareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdjTareaId");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AdjTipoContenido");

                    b.Property<string>("UrlDescarga")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AdjUrlDescarga");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("MensajeTicketId");

                    b.HasIndex("RegistroDiarioId");

                    b.HasIndex("SubidoPor");

                    b.HasIndex("TareaId");

                    b.ToTable("ArchivosAdjuntos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Carpeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CrpId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CrpFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CrpIcono");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("CrpIndiceOrden");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CrpNombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CrpProyectoId");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Carpetas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ColaSoporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClaId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ClaDescripcion");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit")
                        .HasColumnName("ClaEstaActiva");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ClaNombre");

                    b.HasKey("Id");

                    b.ToTable("ColasSoporte");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContenidoMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DocContenidoMarkdown");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocCreadoPor");

                    b.Property<Guid?>("DocumentoPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocDocumentoPadreId");

                    b.Property<bool>("EstaArchivado")
                        .HasColumnType("bit")
                        .HasColumnName("DocEstaArchivado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DocFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DocFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DocIcono");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocProyectoId");

                    b.Property<string>("RutaEsquema")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)")
                        .HasColumnName("DocRutaEsquema");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DocTitulo");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("DocumentoPadreId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("RutaEsquema")
                        .IsUnique();

                    b.HasIndex("Titulo");

                    b.ToTable("DocumentosMarkdown");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LstId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("CarpetaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LstCarpetaId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LstFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("LstIndiceOrden");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LstNombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LstProyectoId");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ListasTareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Marcador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MrcId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MrcEntidadId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("MrcFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("MrcIndiceOrden");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MrcTipoEntidad");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MrcTitulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MrcUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "TipoEntidad", "EntidadId")
                        .IsUnique();

                    b.ToTable("Marcadores");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.MensajeTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MsgId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CorreoRemitente")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("MsgCorreoRemitente");

                    b.Property<string>("CuerpoMensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgCuerpoMensaje");

                    b.Property<bool>("EsNotaInterna")
                        .HasColumnType("bit")
                        .HasColumnName("MsgEsNotaInterna");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("MsgFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreRemitente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("MsgNombreRemitente");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MsgTicketId");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("MensajesTicket");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.PoliticaSla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SlaId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit")
                        .HasColumnName("SlaEstaActiva");

                    b.Property<int>("MinutosPrimeraRespuesta")
                        .HasColumnType("int")
                        .HasColumnName("SlaMinutosPrimeraRespuesta");

                    b.Property<int>("MinutosResolucion")
                        .HasColumnType("int")
                        .HasColumnName("SlaMinutosResolucion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SlaNombre");

                    b.HasKey("Id");

                    b.ToTable("PoliticasSla");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PryId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ClavePrefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PryClavePrefijo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PryDescripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("PryFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PryNombre");

                    b.HasKey("Id");

                    b.HasIndex("ClavePrefijo")
                        .IsUnique();

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ReferenciaEntidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RefId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RefDestinoId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("RefFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("OrigenId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RefOrigenId");

                    b.Property<string>("TipoDestino")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("RefTipoDestino");

                    b.Property<string>("TipoOrigen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("RefTipoOrigen");

                    b.HasKey("Id");

                    b.HasIndex("TipoDestino", "DestinoId");

                    b.HasIndex("TipoOrigen", "OrigenId");

                    b.ToTable("ReferenciasEntidades");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LogId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContenidoMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogContenidoMarkdown");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LogFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LogFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("FechaLog")
                        .HasColumnType("date")
                        .HasColumnName("LogFechaLog");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LogUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaLog")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_FechaLog");

                    b.ToTable("RegistrosDiarios");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroTiempo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RgtId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RgtDescripcion");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("RgtFechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("RgtFechaInicio");

                    b.Property<int?>("MinutosTranscurridos")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("RgtMinutosTranscurridos")
                        .HasComputedColumnSql("DATEDIFF(MINUTE, [RgtFechaInicio], [RgtFechaFin])");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RgtTareaId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RgtUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId", "FechaInicio");

                    b.ToTable("RegistrosTiempo");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RolId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RolDescripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("RolFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RolNombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0001"),
                            Descripcion = "Acceso total, gestión de usuarios y roles.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0002"),
                            Descripcion = "Atiende tickets de soporte.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Agente"
                        },
                        new
                        {
                            Id = new Guid("7a1f0a4e-0c1b-4a8e-9f59-1d0a6b1e0003"),
                            Descripcion = "Gestiona sus tareas, documentos y bóveda.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Miembro"
                        });
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.SecretoBoveda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BvdId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BvdCreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("BvdDescripcion");

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("BvdEntorno");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("BvdFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("BvdFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreClave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("BvdNombreClave");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BvdProyectoId");

                    b.Property<string>("ValorCifrado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BvdValorCifrado");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ProyectoId", "Entorno", "NombreClave")
                        .IsUnique();

                    b.ToTable("BovedaSecretos");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TarId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TarCreadoPor");

                    b.Property<string>("DescripcionMarkdown")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TarDescripcionMarkdown");

                    b.Property<bool>("EsImportante")
                        .HasColumnType("bit")
                        .HasColumnName("TarEsImportante");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("bit")
                        .HasColumnName("TarEsUrgente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TarEstado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TarFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TarFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("TarFechaVencimiento");

                    b.Property<decimal?>("HorasEstimadas")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("TarHorasEstimadas");

                    b.Property<int>("IndiceOrden")
                        .HasColumnType("int")
                        .HasColumnName("TarIndiceOrden");

                    b.Property<Guid>("ListaTareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TarListaTareaId");

                    b.Property<int>("NumeroTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TarNumeroTarea");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTarea"), 100L);

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TarPrioridad");

                    b.Property<Guid?>("TareaPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TarTareaPadreId");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TarTitulo");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("NumeroTarea")
                        .IsUnique();

                    b.HasIndex("TareaPadreId");

                    b.HasIndex("ListaTareaId", "IndiceOrden");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("AgenteAsignadoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckAgenteAsignadoId");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TckAsunto");

                    b.Property<Guid>("ColaSoporteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckColaSoporteId");

                    b.Property<string>("CorreoSolicitante")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TckCorreoSolicitante");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TckEstado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaLimitePrimeraRespuesta")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaLimitePrimeraRespuesta");

                    b.Property<DateTime?>("FechaLimiteResolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaLimiteResolucion");

                    b.Property<DateTime?>("FechaPrimeraRespuesta")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaPrimeraRespuesta");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TckFechaResolucion");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TckNombreSolicitante");

                    b.Property<int>("NumeroTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TckNumeroTicket");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTicket"), 1000L);

                    b.Property<Guid?>("PoliticaSlaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckPoliticaSlaId");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TckPrioridad");

                    b.Property<Guid?>("TareaRelacionadaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TckTareaRelacionadaId");

                    b.HasKey("Id");

                    b.HasIndex("ColaSoporteId");

                    b.HasIndex("NumeroTicket")
                        .IsUnique();

                    b.HasIndex("PoliticaSlaId");

                    b.HasIndex("TareaRelacionadaId");

                    b.HasIndex("AgenteAsignadoId", "Estado");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.TokenRefresco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TkrId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TkrFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TkrFechaExpiracion");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("TkrFechaRevocacion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("TkrTokenHash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TkrUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRefresco");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UsuCorreo");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("UsuEstaActivo");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UsuFechaActualizacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UsuFechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UsuFechaUltimoAcceso");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UsuHashContrasena");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("UsuNombreCompleto");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("UsuNombreUsuario");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UroId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UroFechaAsignacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UroRolId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UroUsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ArchivoAdjunto", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", null)
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.MensajeTicket", null)
                        .WithMany()
                        .HasForeignKey("MensajeTicketId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.RegistroDiario", null)
                        .WithMany()
                        .HasForeignKey("RegistroDiarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("SubidoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Carpeta", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.DocumentoMarkdown", null)
                        .WithMany()
                        .HasForeignKey("DocumentoPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Carpeta", null)
                        .WithMany()
                        .HasForeignKey("CarpetaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", "Proyecto")
                        .WithMany("ListasTareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Marcador", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.MensajeTicket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Ticket", null)
                        .WithMany("Mensajes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroDiario", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.RegistroTiempo", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.SecretoBoveda", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.ListaTareas", "ListaTareas")
                        .WithMany("Tareas")
                        .HasForeignKey("ListaTareaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", "TareaPadre")
                        .WithMany("Subtareas")
                        .HasForeignKey("TareaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ListaTareas");

                    b.Navigation("TareaPadre");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AgenteAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.ColaSoporte", null)
                        .WithMany()
                        .HasForeignKey("ColaSoporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.PoliticaSla", null)
                        .WithMany()
                        .HasForeignKey("PoliticaSlaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaRelacionadaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.TokenRefresco", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.HasOne("SolucionProductividad.Dominio.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolucionProductividad.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.ListaTareas", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Proyecto", b =>
                {
                    b.Navigation("ListasTareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Tarea", b =>
                {
                    b.Navigation("Subtareas");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Ticket", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("SolucionProductividad.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
